src/prefix/mod.rs
src/prefix/tests.rs

I added a mechanism for backwards lookup of the prefix tree (id => text). There's some awkwardness, still:
* to maintain symmetry with the functions that go the other way (text => id), I made the input be an `fst::raw::Output` type, but it means you have to construct an Output before you can start. There's no function overloading in Rust, so that may just be how it goes (or we can sacrifice symmetry and operate on integers, whichever).
* the output is a `Vec<u8>` instead of a String. Think we'll just have to live with that one though, as invalid unicode is allowed to exist in the structure.
Basic algorithmic approach is:
* treat our ID as the budget of value we have left to "spend" on transitions
* set current node to root
* set output to an empty vector
* loop:
* examine the transitions …

Implement inverse prefix lookup, plus tests

---

src/prefix/mod.rs
src/prefix/tests.rs

Per chat, we'll stick with ranges that are exclusive on the top end to be consistent with earlier code and the standard Rust range flavor (`..`).

Return ranges of the form [x,y) instead of [x,y]

---

Cargo.toml
src/lib.rs
src/phrase/mod.rs
src/phrase/util.rs

This PR provides utility functions for building the phrase graph. The words associated with final states in the word graph will each be associated with an integer. `fst::raw::Transition` only allows byte (`u8`) inputs, however. To build the phrase graph, then, we'll represent each word as a fixed-length byte array.  
Length two would only allow 2**16 = 65,536 entries, and that's probably too small.  The number of unique tokens in a corpus can easily be in the hundreds of thousands.
This uses three bytes, giving us 2**24 = 16,777,216 entries, which is most likely overkill.

Add utility function for int <-> byte-array

---

Cargo.toml
src/prefix/boilerplate.rs

Appropriate some mmap-related config stuff from upstream fst.

Fix mmap-related stuff for prefix

---

Cargo.toml
benches/benchmarks.rs
benches/prefix.rs

This PR adds benchmarks for the `PrefixSet` type based on the [criterion](https://github.com/japaric/criterion.rs) library, which adaptively benchmarks functions, basically running just enough to be statistically confident in the output.
I wanted to benchmark a bunch of different things with a common setup, so the pattern I came up with was doing all the setup and saving the results in a reference-counted struct, of which lightweight copies could then be moved into each benchmarking closure. Would be curious to get other people's thoughts as to whether this makes sense and is readable.

Add criterion-based benchmarks for the prefix set

---

profile_osx.sh

This PR adds a kind-of-hacky script for running benchmarks through a profiler. The idea is that you'd write a benchmark runnable through `cargo bench` (see https://github.com/mapbox/fuzzy-phrase/pull/4 ), but you'd run it through this script instead, which would build a special profile-able build of the bench suite, run your benchmark under a profiler, make a pretty interactive graph out of it, and then open it for you. For example, I wrote a prefix benchmark as part of #4 called `prefix/get_by_id`, and running it with the script like this:
```
$ ./profile_osx.sh prefix/get_by_id
```
produces an interactive flamegraph like this (which I've drilled down to the function I care about):
For the moment, I've only written a script that uses `dtrace` for profiling, mostly inspired by [this blog …

Add script for profiling a benchmark on OSX

---

.circleci/config.yml
.codecov.yml

This PR adds a coverage run to the Circle config added in #16 , using [tarpaulin](https://github.com/xd009642/tarpaulin) to collect coverage information and [Codecov](https://codecov.io) to show output. For a sense of how the coverage reports look, see [this branch's coverage info](https://codecov.io/gh/mapbox/fuzzy-phrase/tree/918731653e30579780c2d1035b808d450af2abd7).
The coverage run ends up meaning we run the tests twice; we could do it just once, but tarpaulin seems to insist on rebuilding everything every time rather than benefiting from cache (I assume it needs to rebuild it with some special flags to collect coverage info?), so this way if we're going to fail we fail fast, but just end up waiting a little longer on success, which feels like a good tradeoff to me.
Other odds and …

Coverage using Codecov

---

src/phrase/mod.rs

@apendleton reported that this case broke tests: https://github.com/mapbox/fuzzy-phrase/pull/10/commits/d844b0f419cf56001876a05bd20bec64e66c9d5d#diff-e9b2fd59b2e25d115873b01cd88f3a50R235
What's happening is that, while it is a prefix search, the prefix is an exact match with a single entry in the vocabulary ("street").  So the range is really just the key for the matched word. In other words:
```
sought_max_key == sought_min_key
```
It also happens to be at the edge of the actual range. The only words that can follow `"main"` are `["ave",  "street"]`, and `"street"` is the max of the two, lexicographically speaking.  In other words: 
```
(sought_max_key == sought_min_key) && (sought_max_key == actual_max_key)
```
The code didn't anticipate this.  It's a pretty unlikely case, so I'm …

Handle edge case for phrase range prefix 

---

src/fuzzy/map.rs
src/fuzzy/mod.rs

These are some changes @aarthykc and I worked through reflecting starting to work with the fuzzy map code from the glue-code side. Mostly: it was useful to be able to insert words one at a time rather than all at once at the end, so some of the one-off logic at the end of the build got factored out to insert time.

Fuzzy refactor

---

src/fuzzy/map.rs
src/fuzzy/mod.rs

Several changes here, but nothing major or structural:
* change all word IDs to `u32` and all edit distances to `u8`. Only use usize to look stuff up in arrays, where it's required
* Make lookup return a struct instead of a tuple so the results are easier to work with, and have it include the edit distance, which the glue code needs
* Clean up after my own laziness and do the flagging of multi-IDs in a more grown-up way (no more `BIG_NUMBER`; use bit math instead)
* Clean up after the last round of PRs that introduced some ugliness: the `map`-then-`filter`-then `map` thing in lookup becomes a single `filter_map`, and factor out the thing that determines the expected results from lookup into an `expect` closure
going to merge into my working branch but cc @aarthykc for review to merge into …

Fuzzy keep distance

---

Cargo.toml
benches/benchmarks.rs
benches/phrase.rs
scripts/bench.sh
src/phrase/mod.rs
src/phrase/query.rs

This PR adds some capabilities to running phrase benchmarks on real-world data. It also will add a few new benchmarks to compare the custom solution to a straightforward use of `range` and `StartsWith` functions available from the `fst` library.
New things:
- a script for downloading phrase benchmark data and running phrase benchmarks (can be extended to support others)
- now possible to specify the source for phrase benchmark data using the env variable `PHRASE_BENCH`

[phrase] bench comparison

---

benches/data/phrase_test_sample.txt
benches/phrase.rs
scripts/bench.sh

This change uses a pre-prepared random sample fixture to do benchmarking on `PhraseSet`, in hopes of avoiding the kind of unexpected jiggle seen in #25 comparisons.

using a fixed sample to bench PhraseSet

---

benches/data/phrase_test_sample.txt
benches/phrase.rs

This adds a little more randomness to the benchmarks for phrase graph.  For each query phrase, we randomly pick a length (in words) of the query and truncate it. Then we take the final word and truncate that to a random length.  The prefix range assigned is real, and based on a lexicographically-sorted set of the words in the address data.

[phrase] bench prefix sampling

---

scripts/bench.sh
src/phrase/mod.rs

There's not much change from current master, in terms of performance. Since we're using a random sample each time there's going to be some jiggle. The control here is the `exact_contains` bench, which covers `PhraseSet::contains` (a function that wasn't changed).
| benchmark                    | covers                                         | `master` | this PR  |
|------------------------------|------------------------------------------------|----------|----------|
| phrase/exact_contains        | `PhraseSet::contains`                          | 2.3250us | 1.7847us |
| phrase/exact_contains_prefix | `PhraseSet::contains_prefix` (all full words)  | 2.2820us | 2.4375us |
| phrase/range_contains_prefix | `PhraseSet::contains_prefix` (terminal prefix) | 2.5716us | 2.4619us |
That said: the …

Simpler `PhraseSet::contains_prefix` behavior for ranges

---

.circleci/config.yml

Taurpalin, which we use for coverage, just released [0.6.0](https://www.reddit.com/r/rust/comments/8qcrqb/tarpaulin_060_is_released_and_a_look_at_whats/). Up until now we automatically used the latest version on CI, but our builds started failing with 0.6.0. It looks like this new release introduces some new fanciness for doing accurate coverage of macro-generated code, which both introduces some new dependencies that are tricky to compile, and some brittleness with macro-heavy crates (some of which we depend on either directly or indirectly, like `serde_derive` and `failure`).
I made some attempts in [this branch](https://github.com/mapbox/fuzzy-phrase/tree/fix-tarpaulin) to fix the problems, by building tarpaulin ourselves rather than using a prebuilt one (which fixed some version …

Pin tarpaulin to 0.5.6 for now

---

src/phrase/mod.rs

This PR factors out a part of `contains_prefix_range` to be useful to other functions, and rewrites `contains_prefix` to use it (making the original purpose of `contains_prefix_range` no longer necessary). Already reviewed by @boblannon as part of #31 , but cherry-picked here to be used elsewhere before that branch lands in its entirety.

Refactor contains prefix

---

.circleci/config.yml

Circle is broken, because apparently the Circle-provided Docker image we were using to get a Rust compiler (1.26.0-jessie) has up and vanished. Not sure why that would be. If this happens again, we should consider building our own (and maybe bake Tarpaulin onto it as a bonus).
Going to yolo-merge since all the circle things are blocked.

Switch our docker image to rust 1.26.2

---

benches/fuzzy.rs

The code in each benchmark file outside of the closures gets run every time you run `cargo bench`, regardless of filters. For the `fuzzy` bench code in particular, it tries to check some env vars and open the files they point to, even if users are running other benchmarks and not running the `fuzzy` ones (e.g., with a name filter). At present, even in this circumstance, if the env vars aren't set or the files don't exist, the bencher panics.
This PR instead skips loading the files and attempting to run the benchmarks if the env var isn't set. We should probably eventually instead ship some default data like we do for phrase, or automatically download it within Rust, as we do in glue. Suggesting this PR as a quick unblocker in the meantime, though, as it's not a pressing priority.
cc …

Fix bench panic

---

src/fuzzy/map.rs
src/glue/mod.rs

This PR contains a couple of changes I wanted to sneak under the wire to the on-disk representation of the data structures we build, since once we start to roll out indexes that will eventually be bound for production, these will be harder to change (will require a format version bump and global rebuild).
Specifically:
Anything else anyone wants to tweak before we commit?

On-disk format stability fixes/changes

---

src/phrase/mod.rs
src/phrase/tests.rs

This adds unit tests for the `match_combinations_as_windows` and `match_combinations_as_prefixes` functions.

Window weld unit test

---

src/glue/fuzz_tests.rs
src/glue/mod.rs

Branched off `window-weld`, this PR will add the following: 
- lazy_static that constructs FuzzyPhraseSet, which I did using `ensure-data` in `test_utils`
- Partial_eq for `FuzzyMatchResult` and `FuzzyWindowResult` to check if the phrases un the result are equivalent
- test to check if `fuzzy_match_windows` and `fuzzy_match_multi` give the same result when a "damaged" (phrase that contains a typo) is passed.
cc @boblannon

[WIP] Tests for fuzzy_match_multi and fuzzy_match_windows

---

benches/glue.rs
src/glue/mod.rs

This is a slight optimization for fuzzy_match, fuzzy_match_windows, fuzzy_match_multi, etc., to avoid doing fuzzy lookups for d=0 requests, along with associated benchmarks to measure the improvement. This change makes these queries about three times faster (though to be fair, they were already very fast compared to d=1).

Fast path for d=0 fuzzy matches

---

benches/glue.rs
src/glue/fuzz_tests.rs
src/glue/mod.rs

This PR adds some restrictions on the circumstances in which we fuzzy-match, to improve performance.

Don't attempt fuzzy-matching on one-character words

---

.gitignore
Cargo.lock

We ran into the following error on circle: 
```
error[E0494]: cannot refer to the interior of another static, use a constant instead
--> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/encoding_rs-0.8.13/src/lib.rs:930:42
|
930 |     variant: VariantEncoding::SingleByte(&data::SINGLE_BYTE_DATA.ibm866, 0x0440, 96, 16),
|                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0494]: cannot refer to the interior of another static, use a constant instead
--> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/encoding_rs-0.8.13/src/lib.rs:1000:42
|
1000 |     variant: VariantEncoding::SingleByte(&data::SINGLE_BYTE_DATA.iso_8859_10, 0x00DA, 90, 6),
|                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0494]: cannot refer …
```

Add lockfile

---

benches/prefix.rs
src/glue/mod.rs
src/prefix/boilerplate.rs
src/prefix/mod.rs
src/prefix/tests.rs

Checklist item 3 in #54 requires being able to distinguish between three states for prefix matching: a final phrase token that's just a word prefix (in which case we shouldn't try to token-replace it), a final token that's just a complete word (in which case, we if that word ought to be token-replaced, we should replace it), or one that's both (in which case we should emit both the replaced full word and the unreplaced prefix as candidates during phrase graph traversal). The functions we had in place before didn't supply the necessary level of detail about the matches they found, so this PR replaces the various lookup functions (get, contains, contains_prefix, get_range, etc.) with a single function that returns an enum with methods to interrogate multiple facts about the match.

Refactor prefix lookup functions to support terminal token replacement

---

benches/glue.rs
src/glue/enum_number.rs
src/glue/fuzz_tests.rs
src/glue/mod.rs
src/glue/replacement_tests.rs

This PR makes a bunch of changes around how prefix and non-prefix matching is described both on the input and output side.
Still to do:
fixes #56

Introduce word-boundary params and return values

---

src/glue/bin_tests.rs
src/glue/bins.rs
src/glue/mod.rs
src/phrase/mod.rs

Carmen-cache had one entry per phrase in its index, and also had pre-aggregated combined "bins" with all the geodata for all phrases with a given prefix, to make short autocomplete operations faster. Carmen-core now uses the phrase IDs introduced in #71 rather than strings, so it doesn't have the necessary information to do this kind of pre-aggregation for short phrases. Initial iterations of carmen-core just bucketed data by ID numerically, without regard to how that mapped to actual shared prefixes in real words, and aggregated collections of these bins on the fly, combining them with some non-binned data if the bins didn't precisely align with real ID boundaries between prefixes. This turned out to be really slow at runtime.
This PR reintroduces a mechanism for communicating some …

Add mechanism for automatically binning phrases

---

.travis.yml

Turns off codecov upload per guidance from Security, due to ongoing SEV-1 incident.
Commented off, as it looks like this has been toggled on and off in the past as well, and there is no indication that codecov will not be re-enabled at some point in the future.
cc. @aarthykc

turned codecov off per SEV-1 incident
